version: '2'
services:
  db:
    container_name: webapp-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
    ports:
      - "3333:3306"
    restart: always

  web:
    container_name: webapp
    build: .
    ports:
      - "8888:80"
    volumes:
      - "./webapp:/webapp:z"
    depends_on:
      - db
    restart: always
